"""Initial migration

Revision ID: 5ecbc66db0ac
Revises: 9d3d4002ece5
Create Date: 2025-03-31 11:11:15.248157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecbc66db0ac'
down_revision: Union[str, None] = '9d3d4002ece5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disenos', sa.Column('design_cache_path_minio', sa.String(), nullable=True))
    op.add_column('disenos', sa.Column('design_cache_url_minio', sa.String(), nullable=True))
    op.add_column('pedidos', sa.Column('original_cache_path_minio', sa.String(), nullable=True))
    op.add_column('pedidos', sa.Column('original_cache_url_minio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'original_cache_url_minio')
    op.drop_column('pedidos', 'original_cache_path_minio')
    op.drop_column('disenos', 'design_cache_url_minio')
    op.drop_column('disenos', 'design_cache_path_minio')
    # ### end Alembic commands ###
