"""Initial migration

Revision ID: ce46f210417a
Revises: 11b50faae1b1
Create Date: 2025-03-29 10:29:16.947540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce46f210417a'
down_revision: Union[str, None] = '11b50faae1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disenos', sa.Column('design_cache_path', sa.String(), nullable=True))
    op.add_column('pedidos', sa.Column('original_cache_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'original_cache_path')
    op.drop_column('disenos', 'design_cache_path')
    # ### end Alembic commands ###
